language: go

services:
  - docker

install: true

go:
  - 1.9.x

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.1

script:
  - echo run lint
  - golangci-lint run --disable-all -E errcheck
  - "[ -n $(gofmt -s -l pkg cmd) ] || (echo Code format error; gofmt -s -d -e pkg cmd; false)"
  - DOCKERIZED=y make

notifications:
  email: false

sudo: false
